### ISSUE TITLE
Feature: serialization pragmas

### ISSUE THREAD

**Issue by i-Naji** [treeform/jsony#11]
beside `newHook` and `renameHook`, providing some pragmas like `dontSerialize`, `defaultDeserialize`, `serializationKey` for objects fileds is very useful and make better serialization/deserialization control, [like](https://nim-lang.org/docs/manual.html#userminusdefined-pragmas-custom-annotations):
```nim
type MyObj = object
  a {.dontSerialize.}: int
  b {.defaultDeserialize: 5.}: int
  c {.serializationKey: "_c".}: string
```
any plan for this?
can I work on it?

**Comment by treeform** [comment]
I though about pragmas, but usually my objects are more than just json stuff. I don't want to pollute my core objects with json things.

But I can totally see it being very nice for just objects that exist to make json happy. Which might happen even more often than the core object case.

**Comment by treeform** [comment]
Sorry I decided against serialization pragmas. 

* I want only one want to do things.
* I like hooks slightly better as they are user extendable.
