### ISSUE TITLE
Handling Nullable parameter

### ISSUE THREAD

**Issue by bluemax75** [treeform/jsony#12]
Is there a way of handling a parameter that may be null?
To support a JSON that may come as:

```json
{ "key": 2 }
```
or as
```json
{ "key": null }
```
I already tried using Option this way:
```nim
type 
  Test = object
    key: Option[int]
```
This works for the first JSON but the second one gives the following error
```
Error: unhandled exception: Number expected. At offset: 6 [JsonError]
```

**Comment by treeform** [comment]
Thank you for the bug report! I was just missing a space checking before the `null`. So the space before the null caused this error.

**Comment by bluemax75** [comment]
Wow! That was quick. 
Upgraded to 1.0.1 and Option is working perfect. Thank you!
