### ISSUE TITLE
Any way to get keys starting with underscores?

### ISSUE THREAD

**Issue by jyapayne** [treeform/jsony#20]
I'm trying to transform a json object that has leading underscores in some keys. Is there anyway to deserialize those into an object besides using a `JsonNode`?

```json
{ "_id": "someId" }
```

**Comment by treeform** [comment]
Yes. You can use a `renameHook`:

```nim
type
  IdHolder = object
    id: string

proc renameHook*(v: var IdHolder, fieldName: var string) =
  if fieldName == "_id":
    fieldName = "id"

const jsonString2 = """{ "_id": "someId" }"""
let idHolder = jsonString2.fromJson(IdHolder)
echo idHolder
```

**Comment by jyapayne** [comment]
Ty! I just found it in the code too :)

**Comment by SolitudeSF** [comment]
couldnt this be resolved statically with some pragma annotation?
