### ISSUE TITLE
serializing null values

### ISSUE THREAD

**Issue by VVX7** [treeform/jsony#21]
Hi

What's the best way to omit serializing keys with null values?  
Should I write a dumpHook or is there a better way?

Example:
```
type
    Foo = ref object
        bar: string
        baz: int

let a = Foo(
    bar: "bar"
)

# current
echo a.toJson()
"{"bar":"bar", "baz": null}"

# desired
echo a.toJson()
"{"bar":"bar"}"
```

**Comment by treeform** [comment]
Current out put is `0` not `null`:

```{"bar":"bar","baz":0}```

Because integers value zero is a valid integer value. Not sure you want null or nothing out of that.

But yes dumpHook will be able to accomplish this:

```nim
import jsony

type
    Foo = ref object
        bar: string
        baz: int

let a = Foo(
    bar: "bar"
)

proc dumpHook*(s: var string, v: Foo) =
  s.add '{'
  s.add("\"bar\":")
  s.dumpHook(v.bar)
  if v.baz != 0:
    s.add(", \"baz\":")
    s.dumpHook(v.baz)
  s.add '}'

echo a.toJson()
```

```
{"bar":"bar"}
```

But I don't know why you would want too.

**Comment by VVX7** [comment]
Bad example on my part. `bar` is actually another object. the dumphook gets complicated quickly because these objects are large/complex.

Thanks for the info.
