### ISSUE TITLE
No issue--just a thank you!

### ISSUE THREAD

**Issue by madasebrof** [treeform/jsony#35]
😄 😄 😄 

I was trying to parse super simple json with `std/json`. Was a totally a nightmare.

```json
{ 
  "foo" : "bar",
  "baz": ["a", "b", "c"]
}
```

into:

```nim
type
  Foo = object
    foo: string
    baz: seq[string]
```

You'd think this would be THE EASIEST thing to do. But no. Weird error, need to make `seq[string]` a JsonObject, then cycle through, using a `.toStr()` on each item. Totally weird. Also, breaks when you send to a `proc` (I guess because it's a bizzaro macro).

Worked first time in `jsony`, as you logically expect it to. Deals with missing fields. Etc.

This should replace `std/json`

Thank you!!!

**Comment by Yardanico** [comment]
jsony is nice, but please don't make `std/json` look THAT bad :)

```nim
import std/json

let data = """{ 
  "foo" : "bar",
  "baz": ["a", "b", "c"]
}"""
    
type
  Foo = object
    foo: string
    baz: seq[string]
  

echo parseJson(data).to(Foo)
```

This works just fine

**Comment by madasebrof** [comment]
Bizzaro, totally didn't work when I did it. Was getting weird compile errors. Not sure exactly my original full code. 

I stand corrected!
