### ISSUE TITLE
jsony doesn't handle UTF-16 surrogate pairs

### ISSUE THREAD

**Issue by Yardanico** [treeform/jsony#45]
As of now, jsony doesn't recognize surrogate pairs and just keeps them as-is, resulting in invalid UTF-8 characters:

```nim
import std/json
import pkg/jsony

type
  TestObj = object
    content: string

let
  # A string with 🔒 emoji encoded both as normal UTF-8 and as a surrogate pair
  raw = """{"content":"\uD83D\uDD12🔒"}"""
  parsed = raw.fromJson(TestObj)
  parsedStd = parseJson(raw).to(TestObj)

echo "jsony - ", parsed.content
echo "std/json - ", parsedStd.content
```

Both [std/json](https://github.com/nim-lang/Nim/blob/devel/lib/pure/parsejson.nim#L225) and [nim-json-serialization](https://github.com/status-im/nim-json-serialization/blob/master/json_serialization/lexer.nim#L189) handle surrogates, so I think jsony should also support them.

Found out about this bug from a discussion with @zedeus.

**Comment by treeform** [comment]
That feels like a bug. Why don't I run into it? Almost all json is utf8 encoded? Its rare to get UTF-16 surrogate pairs?

**Comment by zedeus** [comment]
Twitter does it unfortunately, I need this to use jsony for Nitter.

**Comment by treeform** [comment]
I have fixed the surrogate pairs. Thank you for the bug report. 

If it still a problem feel free to reopen with new test case.
