### ISSUE TITLE
[Bug] Using both jsony and status-im/chronicles causes "ambiguous call" compiler error when using `toJson`

### ISSUE THREAD

**Issue by PhilippMDoerner** [treeform/jsony#47]
Version: Jsony 1.1.3 + json_serialization 0.1.0 (as part of [chronicles 0.10.2](https://github.com/status-im/nim-chronicles))

The core issue is, that chronicles uses a package json_serialization and also exports it. Unfortunately, both jsony and json_serialization define `toJson(string)` procs. That isn't further tragic, when I can just specify `jsony.toJson` for my own code. What follows though is that I still get the "ambiguous call" compiler issue, but **now from within jsony**. dom96 assumes that this issue might be related to the timing when nim's generics are being created. I myself have no idea and am completely out of my depth on this one.

These issues happen specifically when using "jsony.toJson()" while both jsony and chronicles are imported in a package. Here a minimal example:

```nim
import chronicles
import jsony

type A = object
  name: string

let a = A(name: "walumba")
echo jsony.toJson(a)
```
This will cause this error during compilation:
> /home/isofruit/dev/testingrounds/src/testingrounds.nim(11, 18) template/generic instantiation of `toJson` from here
/home/isofruit/.nimble/pkgs/jsony-1.1.3/jsony.nim(830, 11) template/generic instantiation of `dumpHook` from here
/home/isofruit/.nimble/pkgs/jsony-1.1.3/jsony.nim(758, 8) template/generic instantiation of `dumpKey` from here
/home/isofruit/.nimble/pkgs/jsony-1.1.3/jsony.nim(696, 20) Error: ambiguous call; both writer.toJson(v: GenericParam, pretty: bool, typeAnnotations: bool) [proc declared in /home/isofruit/.nimble/pkgs/json_serialization-0.1.0/json_serialization/writer.nim(235, 6)] and jsony.toJson(v: T) [proc declared in /home/isofruit/.nimble/pkgs/jsony-1.1.3/jsony.nim(829, 6)] match for: (string)
The terminal process "/usr/bin/bash '-c', 'nim c -r -d:normDebug --threads:on ~/dev/testingrounds/src/testingrounds.nim'" terminated with exit code: 1.

I managed to fix this manually by manipulating `jsony.nim` line 695-697 to explicitly use `jsony.toJson`:

```nim
template dumpKey(s: var string, v: string) =
  const v2 = jsony.toJson(v) & ":"
  s.add v2
```
However, naturally that isn't really long-term viable for me as this change will be gone with the next jsony version. I'm also not sure though whether this actually should be a PR to change the jsony source code or not.

I'm semi-certain it's an indicator for an issue at large, though I don't understand really what it is, even though I managed to find a fix. Thus I'm not sure whom exactly I should inform about the matter. I settled on opening an issue here because I managed to solve it by manipulating jsony's code.  I'd ask for your advice on the matter whether this change to the 3 lines should be incorporated into jsony and whether to also inform the guys from status about the issue.

**Comment by treeform** [comment]
I this this is a problem that you use jsony and json_serialization in the same module. Maybe if you separate them a bit it can work? I don't know how to do the name collisions better. I feel like this is some thing that the Nim language needs to resolve.

I don't know how to help you, so I will be closing the issue. 

Please comment if you find a good solution for others to see.
