### ISSUE TITLE
[Feature request] Parse 0 1 as bool

### ISSUE THREAD

**Issue by artemklevtsov** [treeform/jsony#48]
Sometimes it would be useful to parse 0 1 int as bool.

**Comment by treeform** [comment]
To me that is a little wearied as json has a bool data type, and some languages don't treat 0 or 1 as true and false see https://www.quora.com/Is-1-true-and-0-false-in-programming .

But you get the data you get... so there are always hooks, you can use this to override on how to parse bools:

```nim
type ActiveEntry = object
  active: bool

let activeJson = """{
 "active": 1
}"""

proc parseHook(s: string, i: var int, v: var bool) =
  var tmpInt: int
  parseHook(s, i, tmpInt)
  v = tmpInt == 1

let activeEntry = activeJson.fromJson(ActiveEntry)
echo activeEntry.active
```

**Comment by artemklevtsov** [comment]
Thank you for the reply and hook example.
it would be useful to have all the hooks bundled together somewhere (`examples`?).

**Comment by tandy-1000** [comment]
> Thank you for the reply and hook example. it would be useful to have all the hooks (for the dates, timestamps etc) bundled together somewhere (`examples/`?).

I agree, there are a few of these useful hooks floating around.

**Comment by treeform** [comment]
I am going to close this as I think this is best done with a parseHook by the user code.
