### ISSUE TITLE
Does not parse array json

### ISSUE THREAD

**Issue by Retkid** [treeform/jsony#55]
This is valid json:
```json
[
	["a", "b", "c"]
]
```
however,  jsony cant parse it.
```nim
import jsony
type abc = object
    a : string
    b : string
    c : string
let s = "[["a", "b", "c"]]"
let v = s.fromJson(abc)
echo v
```
however, this library wasn't made with the json spec in mind.

This should return an array of abc.

**Comment by treeform** [comment]
Your object does not match the json you want to parse. 

You can can do this if you want to keep the json the same:
```nim

let s = """[["a", "b", "c"]]"""
echo s.fromJson(seq[seq[string]])
```

Or this if you want to keep the object the same:

```nim

type abc = object
    a : string
    b : string
    c : string
let s2 = """{"a":"something", "b":"otherthing", "c":"yes"}"""
echo s2.fromJson(abc)
```

or if you want an array of abc object use this:

```nim
let s3 = """[{"a":"something", "b":"otherthing", "c":"yes"}]"""
echo s3.fromJson(seq[abc])
```

I hope that helps!

**Comment by treeform** [comment]
Oh and you can also use a parse hook to parse your original json into your object... but its a more advanced thing, you probably don't need that:

```nim
proc parseHook*(s: string, i: var int, v: var abc) =
  var arr: seq[string]
  parseHook(s, i, arr)
  v = abc()
  v.a = arr[0]
  v.b = arr[1]
  v.c = arr[2]

let s = """[["a", "b", "c"]]"""
echo s.fromJson(seq[abc])
```
