### ISSUE TITLE
Expected " but got { instead. At offset: 1048 [JsonError]

### ISSUE THREAD

**Issue by matrix07012** [treeform/jsony#60]
JSON crashes on [this JSON](https://docs.joinmastodon.org/entities/Status/#example) and I'm not sure why.

```
/home/user/.nimble/pkgs/jsony-1.1.3/jsony.nim(547) fromJson
/home/user/.nimble/pkgs/jsony-1.1.3/jsony.nim(429) parseHook
/home/user/.nimble/pkgs/jsony-1.1.3/jsony.nim(347) parseObjectInner
/home/user/.nimble/pkgs/jsony-1.1.3/jsony.nim(47) parseHook
Error: unhandled exception: Expected " but got { instead. At offset: 1048 [JsonError]
```

I'm using Nim 1.6.10 and JSONy 1.1.3 and I'm loading the JSON from a file with `readFile` and just passing the variable to `fromJson`. 
I only added two simple hooks.
```nim
proc parseHook*(s: string, i: var int, v: var DateTime) =
  var str: string
  parseHook(s, i, str)
  v = parse(str, "yyyy-MM-dd'T'hh:mm:ss'.'fffzzz", utc())

proc renameHook*(v: var PreviewCard, fieldName: var string) =
  if fieldName == "type":
    fieldName = "card_type"
```

**Comment by treeform** [comment]
it seems like the you expected the date time to be a string, but its an object. Please include the JSON you are trying to parse in a runnable example.

**Comment by matrix07012** [comment]
> it seems like the you expected the date time to be a string, but its an object. Please include the JSON you are trying to parse in a runnable example.

Sorry for the poor issue. Seems like your guess was correct, I was trying to turn a JSON into a string.

```nim
import jsony

type
  Status* = ref object of RootObj
    application*: string


var test_json = """{
  "application": {
    "name": "Web",
    "website": null
  }
}"""

var status_obj = test_json.fromJson(Status)
```
