### ISSUE TITLE
Non-existing or outdated (?) API in the readme

### ISSUE THREAD

**Issue by mratsim** [treeform/jsony#9]
The readme has many reference to the following API

```Nim
type Entry1 = object
  color: string
var s = """{"extra":"foo"}"""
var v = fromJson[Entry1](s)
doAssert v.color == ""
```

But the library is expecting `var v = s.fromJson(Entry1)`

**Comment by treeform** [comment]
Fixed with https://github.com/treeform/jsony/commit/b6f9d2f3e78b7cc535aeb2a93f3244de9461d056

Had an API change late during development forgot about readme.

Thank you for reporting the issue!
